services:
  authserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./logs:/app/logs # Optional: Bind mount for logging
    restart: unless-stopped
    user: "${APP_UID}" # Ensure this matches the user in your Dockerfile