version: '3.9'

services:
  authserver.api:
    build:
      context: .
      dockerfile: ./AuthServer.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    restart: unless-stopped
