services:
  authserver.api:
    build:
      context: .
      dockerfile: ./AuthServer.API/Dockerfile
    ports:
      - "8085:8085"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    restart: unless-stopped
